#!/usr/bin/bash

# remove multi user nix setup
sudo systemctl stop nix-daemon.socket
sudo systemctl stop nix-daemon.service
sudo systemctl disable nix-daemon.socket
sudo systemctl disable nix-daemon.service
sudo systemctl daemon-reload

sudo mv /etc/bashrc.backup-before-nix /etc/bashrc
sudo mv /etc/profile.d/nix.sh.backup-before-nix /etc/profile.d/nix.sh
sudo mv /etc/zshrc.backup-before-nix /etc/zshrc
sudo mv /etc/bash.bashrc.backup-before-nix /etc/bash.bashrc

sudo rm -rf "/etc/nix" "/nix" "/root/.nix-profile" "/root/.nix-defexpr" "/root/.nix-channels" "/root/.local/state/nix" "/root/.cache/nix" "/home/ch/.nix-profile" "/home/ch/.nix-defexpr" "/home/ch/.nix-channels" "/home/ch/.local/state/nix" "/home/ch/.cache/nix"


exec bash

sh <(curl -L https://nixos.org/nix/install) --daemon --yes

nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update
nix-shell '<home-manager>' -A install
