- name: installing stow
  apt: name=stow
  tags:
    - dotfiles
- name: check if dotfiles directory exists
  ansible.builtin.stat:
    path: "{{ lookup('env', 'HOME') }}/dotfiles"
  register: st
  tags:
    - dotfiles
- name: cloning dotfiles
  ansible.builtin.git:
    repo: "git@github.com:chlouzada/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  when: st.stat.exists == False
  tags:
    - dotfiles
- name: stow dotfiles
  shell: cd $HOME/dotfiles && ./stow
  tags:
    - dotfiles
