- name: populate /etc/environment for gestures on firefox
  lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"
  become: yes
  vars:
    os_environment:
      - key: MOZ_USE_XINPUT2
        value : 1